models:
    detection:
        name: "yolo"
        variant: "n"
        confidence_threshold: 0.30
        iou_threshold: 0.45
        device: "cuda" # change to "cuda" if needed
        classes:
        weights:
            yolo:
                n: "yolov26n.pt"
                s: "yolo26s.pt"
                m: "yolov26m.pt"
                l: "yolov26l.pt"
                x: "yolov26x.pt"
        tracking:
            track_high_thresh: 0.30
            track_low_thresh: 0.15
            new_track_thresh: 0.30
            match_thresh: 0.80
            track_buffer: 30
            min_box_area: 10
            mot20: false

    sparta:
        branch: "CHAD" # SPARTA_C | SPARTA_F | SPARTA_H
        relative: true
        token_config: "t"
        num_kp: 18
        seg_len: 24
        model_num_heads: 2
        model_latent_dim: 64
        dropout: 0.3

        # ACTIVE CHECKPOINTS
        # Set these to whichever dataset you want to use right now.
        IITB:
            ctd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/results-sparta-c/checkpoint_best.pth.tar"
            ftd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/results-sparta-f/checkpoint_best.pth.tar"
            eer_threshold_c: 0.03000000000000001
            eer_threshold_f: 0.0644547895546187

        CHAD:
            ctd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/CHAD/CTD.pth.tar"
            ftd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/CHAD/FTD.pth.tar"
            eer_threshold_c: 0.25
            eer_threshold_f: 0.40

        NWPUC:
            ctd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/NWPUC/CTD.pth.tar"
            ftd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/NWPUC/FTD.pth.tar"
            eer_threshold_c: 0.03000000000000001
            eer_threshold_f: 0.0644547895546187

        SHT:
            ctd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/SHT/CTD.pth.tar"
            ftd: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/Trained_Models/SHT/FTD.pth.tar"
            eer_threshold_c: 0.03000000000000001
            eer_threshold_f: 0.0644547895546187

    pose:
        name: "vitpose"
        variant: "small"
        confidence_threshold: 0.25
        iou_threshold: 0.45
        min_keypoint_confidence: 0.30
        device: "cuda" # change to "cuda" if needed
        fourcc: "XVID"
        save_video: true
        weights:
            vitpose:
                large:
                    config: "../mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large_8xb64-210e_coco-256x192.py"
                    checkpoint: "./td-hm_ViTPose-large_8xb64-210e_coco-256x192-53609f55_20230314.pth"
                base:
                    config: "../mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py"
                    checkpoint: "./td-hm_ViTPose-base_8xb64-210e_coco-256x192-216eae50_20230314.pth"
                small:
                    config: "../mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small_8xb64-210e_coco-256x192.py"
                    checkpoint: "./td-hm_ViTPose-small_8xb64-210e_coco-256x192-62d7a712_20230314.pth"
            rtm:
                l:
                    config: "../mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose-l_8xb256-420e_coco-256x192.py"
                    checkpoint: "./rtmpose-l_simcc-coco_pt-aic-coco_420e-256x192-1352a4d2_20230127.pth"
                m:
                    config: "../mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose-m_8xb256-420e_coco-256x192.py"
                    checkpoint: "./rtmpose-m_simcc-coco_pt-aic-coco_420e-256x192-d8dd5ca4_20230127.pth"
                s:
                    config: "../mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose-s_8xb256-420e_coco-256x192.py"
                    checkpoint: "./rtmpose-s_simcc-coco_pt-aic-coco_420e-256x192-8edcf0d7_20230127.pth"
                t:
                    config: "../mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose-t_8xb256-420e_coco-256x192.py"
                    checkpoint: "./rtmpose-tiny_simcc-coco_pt-aic-coco_420e-256x192-e613ba3f_20230127.pth"

            yolo-pose:
                x: "./yolo26x-pose.pt"
                l: "./yolo26l-pose.pt"
                m: "./yolo26m-pose.pt"
                s: "./yolo26s-pose.pt"
                n: "./yolo26n-pose.pt"

paths:
    input_video: "../videos/surveillance video.mp4"
    pose_output_dir: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/pose_outputs"
    sparta_output_dir: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/evaluation_results_sparta"
    static_prefix: "01_"
    pose_json_suffix: ".json"

inference:
    no_metrics: save
    save_results: save
    save_results_dir: "/home/waleed64/Documents/Human_Centric_Anomaly_Detection_Agent/evaluation_results_sparta"

runtime:
    resize_width: 640
    resize_height: 360
    capture_buffer_size: 2
    use_fp16: true
    min_pose_bbox_area: 2500
    pose_every_n_frames: 3
    sparta_every_n_frames: 5
    max_tracks_per_frame: 8
